name: daily-build-workflow
on:
  schedule:
    # UTCで記述する事、この場合は日本時間 9 時にしたいので -9 して 0 にしてある
    - cron: "0 0 * * *"
    # 明示的な branch の指定はできず、デフォルト branch の latest commit に対して実行される
    # https://help.github.com/en/articles/workflow-syntax-for-github-actions#onschedule

jobs:
  build-windows:
    name: Build momo for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - run: .\build.bat -package
        working-directory: build
        timeout-minutes: 120
  build-macos:
    name: Build momo for macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - run: ./build.sh macos
        working-directory: build
        timeout-minutes: 120
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        name:
          - raspbian-buster_armv6
          - raspbian-buster_armv7
          - ubuntu-16.04_x86_64_ros
          - ubuntu-18.04_armv8_jetson_nano
          - ubuntu-18.04_x86_64
    name: Build momo for ${{ matrix.name }}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: ./build.sh --no-tty --no-mount ${{ matrix.name }}
        working-directory: build
        timeout-minutes: 120
